version: '3'

services:
  flask-app:
    build:
      context: .
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    ports:
      - 32000:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password

volumes:
  mariadb_data:
